# Generated by Django 5.2.8 on 2025-11-19 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(help_text='Manual employee ID (you assign it)', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the employee', max_length=100)),
                ('email', models.EmailField(help_text='Work email address', max_length=254, unique=True)),
                ('position', models.CharField(help_text='Job position or title', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the task', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task')),
                ('completed', models.BooleanField(default=False, help_text='Task completion status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when task was last updated')),
                ('employee', models.ForeignKey(help_text='The employee assigned to this task', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks_app.employee')),
            ],
        ),
    ]
