# Generated by Django 5.2.8 on 2025-11-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the task', null=True),
        ),
    ]
