"""
Django settings for onboarding project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s)+t$=n_9x662+$#7nvo!cc#7erat4a6l(23sfh+(brj1v09zl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',                          # for Django REST Framework
    'rest_framework_simplejwt.token_blacklist', # JWT token blacklist (for BLACKLIST_AFTER_ROTATION)
    'django_filters',                          # for filtering querysets
    'tasks_app',                               # our new app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'onboarding.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'onboarding.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============= REST FRAMEWORK CONFIGURATION =============
REST_FRAMEWORK = {
    # PAGINATION SETTINGS
    # Uses Django REST Framework's default PageNumberPagination
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',

    # PAGE_SIZE: Number of items per page (fixed, cannot be overridden by users)
    'PAGE_SIZE': 10,

    # ============= JWT AUTHENTICATION =============
    # JWT (JSON Web Token) Authentication
    # Stateless authentication - no session storage needed on server
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # JWTAuthentication checks for JWT token in Authorization header
        # Format: "Authorization: Bearer <token>"
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],

    # PERMISSIONS ARE SET AT VIEWSET LEVEL
    # EmployeeViewSet and TaskViewSet use IsAuthenticatedOrReadOnly:
    # - GET requests: Public access (no authentication required)
    # - POST, PUT, PATCH, DELETE: Requires JWT authentication
    #
    # This allows:
    # - Anyone to browse employees and tasks (read-only)
    # - Only authenticated users to create, update, or delete data
}

# ============= JWT TOKEN SETTINGS =============
from datetime import timedelta

SIMPLE_JWT = {
    # HOW LONG TOKENS ARE VALID:
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Access token valid for 60 min
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),     # Refresh token valid for 1 day

    # WHAT IS ACCESS TOKEN vs REFRESH TOKEN?
    # - ACCESS TOKEN: Short-lived token for API requests (60 min)
    #   Used in: Authorization: Bearer <access_token>
    # - REFRESH TOKEN: Long-lived token to get new access tokens (1 day)
    #   When access token expires, use refresh token to get a new access token
    #   without logging in again

    # TOKEN ROTATION: Get new refresh token when using it
    'ROTATE_REFRESH_TOKENS': True,  # Get new refresh token on refresh

    # BLACKLIST: Prevent reuse of old tokens after refresh
    'BLACKLIST_AFTER_ROTATION': True,  # Old tokens can't be used after rotation

    # ALGORITHM: How tokens are signed/encrypted
    'ALGORITHM': 'HS256',  # HMAC with SHA-256

    # SIGNING KEY: Use Django's SECRET_KEY to sign tokens
    'SIGNING_KEY': SECRET_KEY,

    # TOKEN HEADER: How tokens are sent
    'AUTH_HEADER_TYPES': ('Bearer',),  # Use "Authorization: Bearer <token>"
}

